#ifndef __THEME__
#define __THEME__

// Theme
#define PROGRAM_THEME_FOREGROUND FOREGROUND_BLUE
#define PROGRAM_THEME_BACKGROUND BACKGROUND_BLUE

#define PROGRAM_THEME_FOREGROUND_LV1 FOREGROUND_LIGHT_BLUE
#define PROGRAM_THEME_BACKGROUND_LV1 BACKGROUND_LIGHT_BLUE

// Program
#define PROGRAM_FOREGROUND FOREGROUND_BLACK
#define PROGRAM_BACKGROUND BACKGROUND_WHITE
#define PROGRAM_FOREGROUND_REVERSE FOREGROUND_WHITE
#define PROGRAM_BACKGROUND_REVERSE BACKGROUND_BLACK

#define PROGRAM_FOREGROUND_LV1 FOREGROUND_GRAY
#define PROGRAM_BACKGROUND_LV1 BACKGROUND_BRIGHT_WHITE

#define PROGRAM_FOREGROUND_REVERSE_LV1 FOREGROUND_BRIGHT_WHITE
#define PROGRAM_BACKGROUND_REVERSE_LV1 BACKGROUND_GRAY

#endif
